<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VSLive Media Pack (120)_mediaPack</name>
   <tag></tag>
   <elementGuidId>d20c3ace-b7e0-45fd-aa0b-51120ccf90b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mediaCB']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mediaCB</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mediaCB</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9cf1e97-a47b-42cc-b02f-0aad031382b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cb94133f-768d-4f3d-b38c-c2b30fa945b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mediaPack</value>
      <webElementGuid>d284cc9a-8779-4036-8b6e-4fad9602d0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mediaCB</value>
      <webElementGuid>281f61b7-9930-4f35-936f-59489e74d2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>ac6ea029-3f4c-4622-8942-3cce7bd94bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mediaCB&quot;)</value>
      <webElementGuid>3e15107c-2833-4fef-a4ea-d3599daefc5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mediaCB']</value>
      <webElementGuid>e7cef924-abc6-4fdf-8503-05e3bb872257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='confChoices']/input[2]</value>
      <webElementGuid>ce4c43e7-0869-4bb4-9606-272b333f76ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input[2]</value>
      <webElementGuid>7c76de14-aa2b-4e42-b601-f3c820afa164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'mediaPack' and @id = 'mediaCB']</value>
      <webElementGuid>cc604311-832a-47a6-b923-3e98bf349417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
