<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_700.00</name>
   <tag></tag>
   <elementGuidId>a58d0a21-82b7-4482-b46a-0c1c86493aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='regTotal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#regTotal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$700.00&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e306c8f-d9e5-4027-9341-7b1f3aec18c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regTotal</value>
      <webElementGuid>3267955d-89f7-4bfe-b1f9-e3d55ab2d7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$700.00</value>
      <webElementGuid>a8a47951-71f2-402a-8569-42024f17566a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regTotal&quot;)</value>
      <webElementGuid>2ecd7264-81c0-404c-8c8c-5edbbcc6b760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='regTotal']</value>
      <webElementGuid>b2533c25-6d20-4b1f-a746-b66b4637589f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='reg1Aside']/table/tbody/tr[6]/td/span</value>
      <webElementGuid>694e1930-53b3-4f74-8c2a-4ff02c2c7607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL'])[1]/following::span[1]</value>
      <webElementGuid>95335da7-e168-4de6-8ba9-0baeaad136af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='no'])[1]/following::span[1]</value>
      <webElementGuid>d30227fb-ab8a-4db5-aacf-88ee4d4c7696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$700.00']/parent::*</value>
      <webElementGuid>bfbebcad-6f3c-4adc-b3ed-9075679a99a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/span</value>
      <webElementGuid>b285d215-9084-406e-b025-c0b58cee8b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'regTotal' and (text() = '$700.00' or . = '$700.00')]</value>
      <webElementGuid>0d4c6cda-cd71-4008-b585-eb51c1129c65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
